### ISSUE TITLE
Add AWS Session Manager plugin to the dev container

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks-IT/openchallenges#35]
```
$ curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
$ sudo dpkg -i session-manager-plugin.deb
$ rm -f session-manager-plugin.deb
```

Reference: https://docs.aws.amazon.com/systems-manager/latest/userguide/install-plugin-debian-and-ubuntu.html

This plugin is required to execute commands like:

```
AWS_PROFILE=itsandbox-dev AWS_DEFAULT_REGION=us-east-1 aws ecs execute-command ...
```

**Comment by zaro0508** [comment]
you can accomplish this by setting `enable_execute_command=True` in the [ecs.FargateService](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ecs/FargateService.html#aws_cdk.aws_ecs.FargateService) API which we have already done in [service_stack.py](https://github.com/Sage-Bionetworks-IT/openchallenges/blob/dev/openchallenges/service_stack.py)
